/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: b08981dee068e1ed23e4f45a0d8fe70ef7bf7703
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticationRequiredType {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabledForLocalAddresses")]
    DisabledForLocalAddresses,

}

impl std::fmt::Display for AuthenticationRequiredType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Enabled => write!(f, "enabled"),
            Self::DisabledForLocalAddresses => write!(f, "disabledForLocalAddresses"),
        }
    }
}

impl Default for AuthenticationRequiredType {
    fn default() -> AuthenticationRequiredType {
        Self::Enabled
    }
}

