/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: b08981dee068e1ed23e4f45a0d8fe70ef7bf7703
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ColonReplacementFormat {
    #[serde(rename = "delete")]
    Delete,
    #[serde(rename = "dash")]
    Dash,
    #[serde(rename = "spaceDash")]
    SpaceDash,
    #[serde(rename = "spaceDashSpace")]
    SpaceDashSpace,

}

impl std::fmt::Display for ColonReplacementFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Delete => write!(f, "delete"),
            Self::Dash => write!(f, "dash"),
            Self::SpaceDash => write!(f, "spaceDash"),
            Self::SpaceDashSpace => write!(f, "spaceDashSpace"),
        }
    }
}

impl Default for ColonReplacementFormat {
    fn default() -> ColonReplacementFormat {
        Self::Delete
    }
}

