/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: b08981dee068e1ed23e4f45a0d8fe70ef7bf7703
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CreditType {
    #[serde(rename = "cast")]
    Cast,
    #[serde(rename = "crew")]
    Crew,

}

impl std::fmt::Display for CreditType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Cast => write!(f, "cast"),
            Self::Crew => write!(f, "crew"),
        }
    }
}

impl Default for CreditType {
    fn default() -> CreditType {
        Self::Cast
    }
}

