/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: b08981dee068e1ed23e4f45a0d8fe70ef7bf7703
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DatabaseType {
    #[serde(rename = "sqLite")]
    SqLite,
    #[serde(rename = "postgreSQL")]
    PostgreSql,

}

impl std::fmt::Display for DatabaseType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::SqLite => write!(f, "sqLite"),
            Self::PostgreSql => write!(f, "postgreSQL"),
        }
    }
}

impl Default for DatabaseType {
    fn default() -> DatabaseType {
        Self::SqLite
    }
}

