/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: b08981dee068e1ed23e4f45a0d8fe70ef7bf7703
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtraFileResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "movieId", skip_serializing_if = "Option::is_none")]
    pub movie_id: Option<i32>,
    #[serde(rename = "movieFileId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub movie_file_id: Option<Option<i32>>,
    #[serde(rename = "relativePath", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub relative_path: Option<Option<String>>,
    #[serde(rename = "extension", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extension: Option<Option<String>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::ExtraFileType>,
}

impl ExtraFileResource {
    pub fn new() -> ExtraFileResource {
        ExtraFileResource {
            id: None,
            movie_id: None,
            movie_file_id: None,
            relative_path: None,
            extension: None,
            r#type: None,
        }
    }
}

