/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: b08981dee068e1ed23e4f45a0d8fe70ef7bf7703
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExtraFileType {
    #[serde(rename = "subtitle")]
    Subtitle,
    #[serde(rename = "metadata")]
    Metadata,
    #[serde(rename = "other")]
    Other,

}

impl std::fmt::Display for ExtraFileType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Subtitle => write!(f, "subtitle"),
            Self::Metadata => write!(f, "metadata"),
            Self::Other => write!(f, "other"),
        }
    }
}

impl Default for ExtraFileType {
    fn default() -> ExtraFileType {
        Self::Subtitle
    }
}

