/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: b08981dee068e1ed23e4f45a0d8fe70ef7bf7703
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IndexerFlagResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "nameLower", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name_lower: Option<Option<String>>,
}

impl IndexerFlagResource {
    pub fn new() -> IndexerFlagResource {
        IndexerFlagResource {
            id: None,
            name: None,
            name_lower: None,
        }
    }
}

