/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: b08981dee068e1ed23e4f45a0d8fe70ef7bf7703
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MovieStatusType {
    #[serde(rename = "tba")]
    Tba,
    #[serde(rename = "announced")]
    Announced,
    #[serde(rename = "inCinemas")]
    InCinemas,
    #[serde(rename = "released")]
    Released,
    #[serde(rename = "deleted")]
    Deleted,

}

impl std::fmt::Display for MovieStatusType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Tba => write!(f, "tba"),
            Self::Announced => write!(f, "announced"),
            Self::InCinemas => write!(f, "inCinemas"),
            Self::Released => write!(f, "released"),
            Self::Deleted => write!(f, "deleted"),
        }
    }
}

impl Default for MovieStatusType {
    fn default() -> MovieStatusType {
        Self::Tba
    }
}

