/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: b08981dee068e1ed23e4f45a0d8fe70ef7bf7703
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RescanAfterRefreshType {
    #[serde(rename = "always")]
    Always,
    #[serde(rename = "afterManual")]
    AfterManual,
    #[serde(rename = "never")]
    Never,

}

impl std::fmt::Display for RescanAfterRefreshType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Always => write!(f, "always"),
            Self::AfterManual => write!(f, "afterManual"),
            Self::Never => write!(f, "never"),
        }
    }
}

impl Default for RescanAfterRefreshType {
    fn default() -> RescanAfterRefreshType {
        Self::Always
    }
}

